customer: platform
vertical: cdc

# Using a standard node image
# Note: A minimal image such as :alpine works for building
#       but has issues with executing the test steps
from: node:latest

# see ./scripts/build.sh for details
build: sh ./scripts/build.sh
multistage: true
services:
- id: nodeproviderexample
  type: node
  copy:
  # adding required files
  - index.js /dist/index.js
  - package.json /dist/package.json
  - provider.js /dist/provider.js
  # all production node modules required for server-side-rendering
  - node_modules /dist/node_modules
  exec: cd dist && npm start
  check: true
  # These are the defaults and
  # needs to be enhanced for most services
  resources:
    requests:
      memory: "500Mi"
      cpu: "200m"
    limits:
      memory: "1000Mi"
      cpu: "1000m"

# Specifies the files executed for tests on each environment. Need to be executable 'chmod +x'
tests:
 - stage: pp
   test: chmod 777 scripts/tests.sh && ./scripts/tests.sh

watchers:
 - navyateja.otturu@ggktech.com
 - rohith.vallabhaneni@ggktech.com

slack-channels:
 - '@peng-cdc'